---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brian.
--- DateTime: 08/01/2022 18:58
---
local hashing = require("cryptography.pure_lua_SHA.sha2")
local _M = {}

function _M.getWelcomeMessage()
 return "Hi Brian, your Lua module is working when imported into app.lua"
end

function _M.getSha256HashOfString(string)
 return hashing.sha256(string)
end

function _M.getTimeStamp()
 return os.date ("date %x time %H:%M:%S:%m")
end

return _M
