---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by brian.
--- DateTime: 06/02/2022 19:14
---
--TODO: figure out how to custom-secure core blockchain host with its nodes... encrypted Json Web Token perhaps??
local socket = require("socket")
local http = require("socket.http")
local ltn12 = require("ltn12")

local _M = {}

function _M.sendGetRequest(url)
    local path = url
    local response_body = { }

    local res, code, response_headers, status = http.request {
        url = path,
        method = "GET",
        sink = ltn12.sink.table(response_body)
    }

    return { responseStatus = status, responseBody = response_body }
end

function _M.sendPostRequest(url, payload, customHeaders)
    local path = url
    local response_body = { }

    local res, code, response_headers, status = http.request {
        url = path,
        method = "GET",
        headers = customHeaders or {
            ["Authorization"] = "Maybe you need an Authorization header?",
            ["Content-Type"] = "application/json",
            ["Content-Length"] = payload:len()
        },
        source = ltn12.source.string(payload),
        sink = ltn12.sink.table(response_body)
    }
    socket.luup.task('Response: = ' .. table.concat(response_body) .. ' code = ' .. code .. '   status = ' .. status, 1, 'Sample POST request with JSON data', -1)

    return { responseStatus = status, responseBody = response_body }
end

function _M.sendPatchRequest(url, payload)
   --TODO
end

function _M.sendPutRequest(url, payload)
    --TODO
end

return _M